/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.30 from the
 * contents of Stats.xs. Do not edit this file, edit Stats.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Stats.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"


#line 21 "Stats.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 165 "Stats.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Stats.xs' */


XS_EUPXS(XS_Local__Stats_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 190 "Stats.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Local::Stats macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Local::Stats macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Local::Stats macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 267 "Stats.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Stats.xs' from 'const-xs.inc' */


XS_EUPXS(XS_Local__Stats_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_add)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "r_self, name, value");
    {
	SV *	r_self = ST(0)
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	double	value = (double)SvNV(ST(2))
;
#line 21 "Stats.xs"
		// Check object
		if (!( SvOK(r_self) && SvROK(r_self) )) croak("object must be a hashref");
		SV *_self = SvRV(r_self);
		// Check type
		if (SvTYPE(_self) != SVt_PVHV) croak("object must be a hashref");
		// Cast to hash type
		HV *self = (HV*)_self;
		// Check keys
		if (!( hv_exists(self, "metrics", 7) && hv_exists(self, "code", 4) ))
			croak("object must contain keys 'metrics' and 'code'");
		// Fetch values
		SV **_metrics = hv_fetchs(self, "metrics", 0);
		SV **r__code = hv_fetchs(self, "code", 0);
		if (!( _metrics && r__code )) croak("Non allow NULL in metrics and code values");

		SV *r_metrics = *_metrics;
		if (!( SvOK(r_metrics) && SvROK(r_metrics) )) croak("metrics must be a hashref");
		SV *__metrics = SvRV(r_metrics);
		if (SvTYPE(__metrics) != SVt_PVHV) croak("metrics must be a hashref");
		HV *metrics = (HV*)__metrics;

		// Check code
		SV *__code = *r__code;
		if (!SvOK(__code)) croak("config must be a ref");
		SV *_code = SvRV(__code);
		if (SvTYPE(_code) != SVt_PVCV) croak("code must be a coderef");

		double old_sum, new_sum, new_avg, old_min, old_max, new_min, new_max;
		int old_cnt;

		if ( hv_exists(metrics, name, strlen(name)) ) {
			SV **r__config = hv_fetch(metrics, name, strlen(name), 0);
			if (!r__config) croak("Non allow NULL in metric config");
			SV *__config = *r__config;
			if (!SvOK(__config)) croak("config must be a hashref");
			SV *_config = SvRV(__config);
			if (SvTYPE(_config) != SVt_PVHV) croak("config must be a hashref");
			HV *config = (HV*)_config;

			if ( hv_exists(config, "sum", 3) ) {
				old_sum = SvNV(*(hv_fetch(config, "sum", 3, 0)));
				new_sum = old_sum + value;
				hv_store(config, "sum", 3, newSVnv(new_sum), 0);
			}
			if ( hv_exists(config, "cnt", 3) ) {
				old_cnt = SvIV(*(hv_fetch(config, "cnt", 3, 0)));
				hv_store(config, "cnt", 3, newSViv(old_cnt + 1), 0);
			}
			if ( hv_exists(config, "avg", 3) ) {
				new_avg = new_sum / (old_cnt + 1);
				hv_store(config, "avg", 3, newSVnv(new_avg), 0);
			}
			if ( hv_exists(config, "min", 3) ) {
				old_min = SvNV(*(hv_fetch(config, "min", 3, 0)));
				new_min = (old_min < value) ? old_min : value;
				hv_store(config, "min", 3, newSVnv(new_min), 0);
			}
			if ( hv_exists(config, "max", 3) ) {
				old_max = SvNV(*(hv_fetch(config, "max", 3, 0)));
				new_max = (old_max > value) ? old_max : value;
				hv_store(config, "max", 3, newSVnv(new_max), 0);
			}

		} else {
			// Call function
			HV* conf = newHV();
			dSP;
			ENTER;
	        SAVETMPS;
	        PUSHMARK(SP);
	        EXTEND(SP, 1);
	        mPUSHp(name, strlen(name));
	        PUTBACK;

	        int count = call_sv(_code, G_ARRAY);
	        int i;
	        SPAGAIN;
	        // Now arguments in stack
			// Catch them all
	        for (i = 0; i < count; i++) {
	        	char * arg = POPp;

	        	if (strcmp(arg,"cnt") == 0) {
	        		hv_store(conf, arg, 3, newSViv(1), 0);
	        	}  
	        	else if (strcmp(arg,"sum") == 0) {
	        		hv_store(conf, arg, 3, newSVnv(value), 0);
	        	}
	        	else if (strcmp(arg,"avg") == 0) {
	        		hv_store(conf, arg, 3, newSVnv(value), 0);
	        		hv_store(conf, "sum", 3, newSVnv(value), 0);
	        		hv_store(conf, "cnt", 3, newSViv(1), 0);
	        	}
	        	else if (strcmp(arg,"min") == 0) {
	        		hv_store(conf, arg, 3, newSVnv(value), 0);
	        	}
	        	else if (strcmp(arg,"max") == 0) {
	        		hv_store(conf, arg, 3, newSVnv(value), 0);
	        	}
	        }
	        FREETMPS;
	        LEAVE;
	        hv_store(metrics, name, strlen(name), newRV((SV *)conf), 0);
		}
#line 395 "Stats.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Local__Stats_stat); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_stat)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "r_self");
    {
	SV *	r_self = ST(0)
;
	SV *	RETVAL;
#line 131 "Stats.xs"
		// Check object
		if (!( SvOK(r_self) && SvROK(r_self) )) croak("object must be a hashref");
		SV *_self = SvRV(r_self);
		// Check type
		if (SvTYPE(_self) != SVt_PVHV) croak("object must be a hashref");
		// Cast to hash type
		HV *self = (HV*)_self;
		// Check keys
		if (!( hv_exists(self, "metrics", 7) && hv_exists(self, "code", 4) ))
			croak("object must contain keys 'metrics' and 'code'");
		// Fetch metrics and code
		SV **r__metrics = hv_fetchs(self, "metrics", 0);
		SV **r__code = hv_fetchs(self, "code", 0);
		if (!( r__metrics && r__code )) croak("Non allow NULL in metrics and code values");

		SV *__metrics = *r__metrics;
		if (!( SvOK(__metrics) && SvROK(__metrics) )) croak("metrics must be a hashref");
		SV *_metrics = SvRV(__metrics);
		if (SvTYPE(_metrics) != SVt_PVHV) croak("metrics must be a hashref");
		HV *metrics = (HV*)_metrics;

		SV *__code = *r__code;
		if (!SvOK(__code)) croak("config must be a ref");
		SV *_code = SvRV(__code);
		if (SvTYPE(_code) != SVt_PVCV) croak("code must be a coderef");

		HV* result = newHV();

		HV *copy_metrics = newHV();
		copy_metrics = metrics;

		I32 keys = hv_iterinit(copy_metrics);

		SV *value;
		HV* _value;
		HV* copy_value = newHV();
		char *key = NULL;
		int key_length;
		int i;
		for (i = 0; i < keys; i++) {
			char *key = NULL;

			value = hv_iternextsv(copy_metrics, &key, &key_length);
			_value = (HV*)value;

			// HV* conf = newHV();
			// ENTER;
	  //       SAVETMPS;
	  //       PUSHMARK(SP);
	  //       EXTEND(SP, 1);
	  //       mPUSHp(key, key_length);
	  //       PUTBACK;
	  //       int count = call_sv(_code, G_ARRAY);
	  //       SPAGAIN;
	  //       printf("count = %d\n", count);
	  //       int j;

	  //       for (j = 0; j < count; j++) {
	  //       	char * arg = POPp;
	  //       	printf("arg %d = %s\n", j, arg);
	  //       	// double val = SvNV(*(hv_fetch(_value, arg, 3, 0)));
	  //       	// if ( hv_exists(_value, arg, 3) ) {
	  //       	// SV** _val = hv_fetch(_value, arg, 3, 0);
	  //       	// printf("arg %d = %s\n", j, arg);
	  //       	// 	// SV *val = *_val;
	  //       	// hv_store(conf, arg, 3, 30, 0);
	  //       	// }
	  //       }
	  //       PUTBACK;
	  //       FREETMPS;
	  //       LEAVE;
	        // hv_store(result, key, key_length, newRV((SV *)conf), 0);
		}

		SV** _val = hv_fetch(_value, "sum", 3, 0);

		RETVAL = _value;
#line 489 "Stats.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Local__Stats); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Local__Stats)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Local::Stats::constant", XS_Local__Stats_constant);
        newXS_deffile("Local::Stats::add", XS_Local__Stats_add);
        newXS_deffile("Local::Stats::stat", XS_Local__Stats_stat);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

